### ISSUE TITLE
Switching from Travis to Github Actions

### ISSUE THREAD

**Issue by LucaCappelletti94** [laysakura/trie-rs#24]
Hi - I noticed that the Travis CI link is broken. I had several of those myself since when Travis switched to a premium-only CI.

If that is okay for you, I will make a pull request changing the travis setup for a GitHub actions setup.

Best,
Luca

**Comment by shanecelis** [comment]
Once issue #30 is dealt with this should be complete. Thanks, Luca, for getting the ball rolling on it.
