### ISSUE TITLE
Change source of GitHub pages

### ISSUE THREAD

**Issue by shanecelis** [laysakura/trie-rs#30]
Hi Sho,

@LucaCappelletti94 got the ball rolling on converting the travis CI to Github actions. (Thanks, Luca!) I've given it another push to get the documentation and benchmarks generated as well. In doing so it'll be helpful to adjust one setting on the trie-rs repository. We'd like to populate the trie-rs' pages from GitHub actions instead of the `gh-pages` branch. To change this, go to trie-rs Settings, then Pages, then set the source to Github Actions. That should be it. Thanks, Sho.

-Shane

**Comment by laysakura** [comment]
Did it.

<img width="1373" alt="image" src="https://github.com/laysakura/trie-rs/assets/498788/4bcca7e5-16f1-4816-859c-6bf3a0601e0c">

Thanks @shanecelis and @LucaCappelletti94 !

**Comment by shanecelis** [comment]
Thanks, Sho!
